version: 2.0
jobs:

  build-wordpress:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-cache-{{ checksum "wordpress/composer.lock" }}
            - composer-cache
      - run:
          name: Build WordPress
          command: |
            make start
      - save_cache:
          key: composer-cache-{{ checksum "wordpress/composer.lock" }}
          paths:
            - wordpress/vendor
            - wordpress/wp-content/plugins
      - persist_to_workspace:
          root: wordpress
          paths:
            - '.'

  build-theme:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: wordpress
      - restore_cache:
          keys:
            - node-cache-{{ checksum "wordpress/wp-content/themes/zest/package-lock.json" }}
            - node-cache
      - run:
          name: Install theme dependencies
          command: |
            cd wordpress/wp-content/themes/zest
            npm install
      - save_cache:
          key: node-cache-{{ checksum "wordpress/wp-content/themes/zest/package-lock.json" }}
          paths:
            - wordpress/wp-content/themes/zest/node_modules
      - run:
          name: Build
          command: |
            cd wordpress/wp-content/themes/zest
            npm run build
      - persist_to_workspace:
          root: wordpress
          paths:
            - '.'

  deploy:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "15:17:f1:78:e7:ea:01:99:d5:a3:32:d9:c2:aa:81:b7"
      - attach_workspace:
          at: wordpress
      - run:
          name: Deploy to staging
          command: |
            sudo apt install rsync
            echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            rsync -avO --no-perms --ignore node_modules --ignore wordpress/wp-config.php ./wordpress/ sam@sjd.co:/var/www/testing.sjd.co/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-wordpress
      - build-theme:
          requires:
            - build-wordpress
      - deploy:
          requires:
            - build-theme